### ISSUE TITLE
[Góc nhìn Test Phần 1] Testing có đang làm chậm quá trình phát triển phần mềm.

### ISSUE THREAD

**Issue by Jacobvu84** [Jacobvu84/Automated-Software-Testing#38]
Hoạt động testing được coi là một phần trong quy trình phát triển phần mềm dù ở bất cứ mô hình nào. Chỉ khác ở chỗ nó nên được thực hiện lúc nào và làm ra làm sao ?

Cá nhân tôi chứng kiến và trải qua một số công ty và cho tới bây giờ cũng nhận ra nhiều mặt hạn chế. Xin được chia sẻ từ góc nhìn của tôi.

#### 1. Vấn đề nội tại trong nhóm QA.
Với cách làm truyền thống thì testing được coi như là chốt chặn cuối cùng trước khi release. Điều này ko sai nhưng nó vô tình làm cản trở và làm chậm quá trình release. Thông thường khi release một phiên bản mới từ lúc tìm hiểu yêu cầu cho tới khi hoàn thành. DEv mất x ngày và Test mất y ngày nhưng nếu Dev tốn thêm z ngày mà vẫn muốn đảm bảo tiến độ thì đồng nghĩa việc test chỉ còn y-z ngày. 

Đó là lý do vì sao đôi khi tester phải OT. Ngay cả khi chuẩn chỉ ai làm đúng thời gian của người đó thì trong hoạt động test vẫn còn lộ ra nhiều bước tốn thời gian, trong đó có việc update kết quả test cases. Nó hoàn toàn làm bằng tay. Các bạn Tester phải nhập từng chữ passed lên công cụ quản lý như excel, testrail, testlink.... hoặc các công cụ quản lý test khác, mà chỉ để phục vụ cho công tác báo cáo. Cá nhân tôi nghĩ những cases passed ko làm hại ai. Nên dù quản lý hay dev có biết hay ko biết nó cũng chẳng ảnh hưởng gì. Chúng ta chỉ cần tạo báo cáo liệt kê các cases KHÔNG PASS trong test plan là đủ. 

Một số công ty tổ chức nhân sự chồng chéo. Họ tách Tester thành một department riêng và manager của bộ phận này sẽ làm nhiều vụ điều tiết người cho các dự án, thu thập báo cáo công việc các thành viên. Điều này có vẻ như tốt nhưng nếu họ không chọn việc show các kết quả test dựa trên các chỉ số xanh, đỏ ( pass, fail) để báo cáo thì có lẽ tester ko tốn thời gian để thực hiện các công việc không mất ý nghĩa như đã nêu trên. Những điều họ thường làm chỉ để lý giải cho việc họ đang cố gắng đạt KPI nào đó hoặc làm màu thành tích với các thông số. Về mặt ý nghĩa là ko cần thiết chỉ để "diễn" về mặt thành tích cá nhân hay phòng ban. 

Bạn biết đấy Tester thường có sự kiên nhẫn vì công việc nó đòi hỏi sự tỷ mẫn, chi tiết. Do đó dễ nhận thấy nữ chiếm đa số vì một trong tính cách của nữ là sự kiên nhẫn. Nhưng họ chỉ có y ngày trong một chu kỳ phát triển phần mềm và liệu những gì chi tiết, tỷ mẫn mà lại làm nhanh. Liệu có phải là xung đột. Mà không làm nhanh thì lại làm chậm quá trình release. 

#### 2. Vấn đề chung trong toàn bộ dự án
Hoặc động testing luôn thực hiện sau khi Dev đã hoàn thành xong công việc của mình: Đây là cách làm nó mang ý nghĩa làm an lòng người quản lý dự án hoặc các ông chủ.

Về cơ bản testing là một trong những hoạt động để phát triển phần mềm nhưng với các làm này khi mà gạo đã vào nồi và lên lửa thì chưa biết nó thành cơm hay cháo.  Có nghĩa là sau khi đã thành hình họ mới test thì nó chỉ mang ý nghĩa checking chứ không còn test nữa. Nên gọi họ là checker thì đúng hơn là tester. Việc của họ là báo lại cho bạn biết kết quả nồi cơm đó đã chín chưa để mang cho người dùng ăn. Nếu nó thành cháo thì báo lại nó là cháo hoặc thậm trí tệ hơn nó bị khê cháy và khét. Vậy sau khi nhận được kết qủa này ta làm gì? Đi mà rửa nồi mà nấu lại nồi khác thôi nhưng gạo ở đâu ra mà nấu lại. Tốn chi phí cho ông chủ. 

Hãy coi phần mềm là nồi cơm đó. Khi mà test chỉ thực hiện công việc của mình sau khi dev làm xong. Họ phát hiện ra bug sẽ lại tốn thời gian đưa phần mềm trở lại cho dev để việc bảo trì, sửa chữa, fix bug hoặc làm mới cái thiếu. Lại gây chậm trễ.

Tóm lại quy trình có nhiều cái hạn chế. Bản thân việc thực hiện test cũng còn nhiều sự hạn chế mất thời gian. 

Nhiều nơi đã **áp dụng Agile** để mọi thứ nhanh hơn nhưng lại biến nó **thành mô hình thác nước thu nhỏ**. Chỉ là họ chắt nước từ bình lớn sang các bình nhỏ hơn còn nước trong bình vẫn mùi vị ấy

Vậy làm sao để giải quyết vấn đề này
- Không cần quan tâm các chúng ta vận hành quản lý như thế nào. Nhưng tập trung cho sự phản hồi sớm hơn là báo cáo. 
- Thay vì hoạt động độc lập như một internal service, thực hiện Test sau khi hoàn thành thì hãy test nó trước khi làm.

Làm sao để thực hiện nó. Làm sao để có phản hồi nhanh nhất, làm sao để tất cả đều chung trên một chiếc thuyền. Từ khoá là tự động hoá ( Automation Test)

Nhưng hãy xem họ đã sai lầm thế nào trong việc triển khai này trong phần 2

**Comment by doanjv** [comment]
Bài viết thú vị. Bản thân em đã làm test automation ở một số công ty và hiện tại em thấy automation vẫn chưa thể hiện được vai trò xứng đáng. Những thủ tục báo cáo, deadline để implement đủ số lượng test case từ phía manual. Cái quan trọng là thấy là thiếu sự đánh giá cái nào đang cần để automate. Vì em thấy test automation chỉ mạnh ở một số góc độ của dự án, nếu tận dụng tốt sẽ mang lại hiệu quả tốt, nếu không sẽ trở nên lạc lõng trong dự án.
Hóng phần 2 của anh.
